[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"
solana_version = "2.2.12"

[features]
resolution = true
skip-lint = false

[programs.localnet]
raffle_vault = "BRWhr8mqPoi9gsKrie32hWdLU2jWKBh3PixLXg4sAytA"

[programs.devnet]
raffle_vault = "BRWhr8mqPoi9gsKrie32hWdLU2jWKBh3PixLXg4sAytA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
